### ISSUE TITLE
Update Spring Boot version

### ISSUE THREAD

**Issue by XSpielinbox** [flapdoodle-oss/de.flapdoodle.embed.mongo.spring#33]
The main branch is on the same state as the [spring-3.0.x](https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo.spring/tree/spring-3.0.x) branch.

- [ ] 1. the latest 3.0.x version of Spring boot is 3.0.10. Please consider upgrading to it (the `pom.xml` currently uses 3.0.4)
- [ ] 2. The `README.md` states, the project would be based on Spring Boot 2.7.x, which it isn't. Please update that accordingly.
- [ ] 3. In the `pom.xml` you define a separate `spring.boot.configuration-processor` version. Please consider using the same  `spring.boot.version` version.
- [ ] 4. Even the commercial support for Spring Boot 2.5.x ended more than two weeks ago, but it is still has it's own auto-configuration, that is officially supported. Spring Boot 3.1.x released almost 4 month ago now, but there still is no auto-configuration nor official support (the Spring Boot 3.0.x integration does work completely fine with Spring Boot 3.1.x too, though). Please consider adding a Spring Boot 3.1.x auto-configuration.

If you wish, I can also open a PR.

**Comment by michaelmosmann** [comment]
@XSpielinbox 
1) As all spring dependencies are only "provided", does it affect the dependency resolution somehow?
2) "based on spring 2.7.x" means that this code is an clone of an clone of the spring 2.7.x integration from the spring project, but maybe this knowledge is not of any use.
3) will do
4) how does this differ from the spring boot 3.0.x integration? To maintain a 4th fork of this code should come with some kind of benefit..

**Comment by michaelmosmann** [comment]
1.) ok.. 
2.) Until spring 2.7 the spring integration code came from the spring project itself.. so i could use their 2.5, 2.6 and 2.7 code fragments to apply the changes.. they stopped providing their own code from 2.7 on (funny story).
4.) I don't make the rules.. and i do not use spring in my projects.. so i can only guess why they are releasing a new version if most parts don't really change.. i would prefer to have as few versions as possible .. but i will create an release for spring 3.1 because of 1) .. just some numbers (last month integration downloads from sonatype nexus repo):
- 2.5: 60
- 2.6: 450
- 2.7: 6.000
- 3.0: 50.000
